### ISSUE TITLE
Height editor save value with comma separator

### ISSUE THREAD

**Issue by kendzi** [kendzi/kendzi3d#52]
Source: http://forum.openstreetmap.org/viewtopic.php?pid=518325#p518325

**Comment by majkaz** [comment]
Any change? I still get this (probably because the system comma separator is set as comma - czech settings) in the 1.0.191.
Any workaround possible?

**Comment by kendzi** [comment]
No workaround. It has to be fixed. Please check version 1.0.192

**Comment by majkaz** [comment]
Thank you, works perfect now.
