### ISSUE TITLE
Not working in last JOSM release

### ISSUE THREAD

**Issue by yopaseopor** [kendzi/kendzi3d#62]
Hi!
I have updated as usual my version of JOSM. Now is 11639 version. with this version and without changes on the models library Kendzi's World is empty: no roads, no buildings, no models.
I have tried to install from 0 on another computer...and the result is the same.
Am I doing wrong anything?
Is any bug with this new version?

(With 11425 Kendzi is working well)
Thanks

**Comment by kendzi** [comment]
I will check it tomorrow

**Comment by kendzi** [comment]
fixed in 1.0.195
