### ISSUE TITLE
Problems with models wit a " - " character

### ISSUE THREAD

**Issue by yopaseopor** [kendzi/kendzi3d#63]
Hi!
I have one problem with traffic signs model selector.
Today when I taste the new version I discovered one thing:
Models which have in their traffic code a hyphen character ( - ) don't work.
I supose it is because hyphen is the character chosen to invert the search in JOSM but I don't know how can I fix it. For example you can try with any traffic sign of US with a Hyphen or Poland (PL:A-1 is a good example)

How can I do these searchs?
You can check https://raw.githubusercontent.com/yopaseopor/traffic_signs_kendzi3D/master/US_traffic_signs.xml for example.

Thanks
yopaseopor

**Comment by kendzi** [comment]
Char "-" is inside tag value so it should not affect search. I just tested it inside build in josm search and looks like it is working fine. Are you sure that there is not some miss spell in your filter? 
If not please send exact filter value here and all tags from way what should be searched but is not.

**Comment by yopaseopor** [comment]
I check again the issue,as the issue with character " ' " it is in the part
of the name of the file (which for semiautomated build of the models is the
same of the tag -with hyphen-) . I will erase all hyphens in file names and
URL's and I think it will work.
Thank you for your attention
