### ISSUE TITLE
Question about functionality

### ISSUE THREAD

**Issue by mr-j0nes** [kendzi/kendzi3d#69]
Hi , great job with the plug-in. I went through the documentation and played around with it, but I do not understand completely the functionality.

E.g. I would like to see a menu of the possible roofs types and/or colors and apply it to the selected building. Is it possible to do that with this plug-in ?

Additionally maybe a color picker to get the roof color from the bing imagery would be a good idea too...

**Comment by kendzi** [comment]
It is not inside that plugin, but you could select roof using additional template:
Menu Preferences (F12) > Tab Map Settings > Tab Tagging Presets > Chose "3D Simple Buildings"
Then after choosing building you can chose roof shape inside that template.

**Comment by mr-j0nes** [comment]
Didn't know about that, thanks a lot.
