### ISSUE TITLE
Update to latest JOSM

### ISSUE THREAD

**Issue by don-vip** [kendzi/kendzi3d#71]
We have removed a lot of deprecated API as advertised on the mailing list, see https://josm.openstreetmap.de/ticket/15310

As a result this plugin is no longer compatible, can you please update it?

Thanks.

**Comment by kendzi** [comment]
I will handle it as soon possible.

**Comment by kendzi** [comment]
Could you please generate new maven snapshot of josm?

**Comment by don-vip** [comment]
I'm on it. I almost just killed the JOSM server in upgrading Nexus Repository, I think we have a configuration problem, I let you know.

**Comment by don-vip** [comment]
It should be OK now.

**Comment by kendzi** [comment]
Fixed
