### ISSUE TITLE
Support crossings/passage routes/thoroughfare

### ISSUE THREAD

**Issue by natrius** [kendzi/kendzi3d#80]
Hello, 

i would like to tag a caste in 3d while checking with kendzi but i was not able to see a passage other than split the building in 3 parts and tag the middle-one with a min_height. The problem - thats not true.
So i found this https://wiki.openstreetmap.org/wiki/DE:3D-building/Durchfahrt wikisite and i like it, its simple, intuitive and there is no need to split the building. 
But unfortunately it does not show up in kendzi3d.

Usecases:
Castle-Entrances
Old towns, there are sometimes passes through buildings that are built wall to wall.

Is there already another tag-set that is used for that or is it not implemented yet?

Greets

**Comment by kendzi** [comment]
Sorry, it is not implemented at all. I don't known any 3D render for OSM which support it. I'm not sure even if that tagging schema is accepted as it may by only idea.

**Comment by natrius** [comment]
Are you aware about any other tagging schema for a passage? Otherwise i will try to get this schema accepted.

**Comment by natrius** [comment]
According to https://wiki.openstreetmap.org/wiki/Key:tunnel tunnel=building_passage is approved and a used tag and is a valid usecase. The width, height is just there to clarify it. So, the only not approved tag would be passage_type=<Value> and would be just to clarify it further.
