### ISSUE TITLE
Not recognizes Jogl after JOSM update

### ISSUE THREAD

**Issue by Gustl22** [kendzi/kendzi3d#86]
Hi, this error message appears after I installed new Josm (deleted previous preferences) and Kendzi3d-Plugin:

![clipboard04](https://user-images.githubusercontent.com/18537755/44082634-152ada04-9fb2-11e8-9eda-bb49442754a1.jpg)

Hitting "Download and Restart"-Button doesn't have an impact.
I then installed "josm-jogl" manually, but the error message remains. Here is my plugin folder:

![clipboard05](https://user-images.githubusercontent.com/18537755/44082774-7d29afa4-9fb2-11e8-98b7-bc72076ecb82.jpg)

_Josm 14066
Java 1.8.0_171
Kendzi3d 1.0.204
Kendzi3d-resources 0.0.2_

Sorry if this belongs to Josm and not to Kendzi3d...

**Comment by kendzi** [comment]
I'm manage Jogl plugin too, I will test it.

**Comment by kendzi** [comment]
I made mistake with releasing jogl plugin, it is fixed now.

**Comment by Gustl22** [comment]
Thank you very much :D
