### ISSUE TITLE
Doesn't seem to work with Java 10 (Windows)

### ISSUE THREAD

**Issue by jbelien** [kendzi/kendzi3d#89]
Hi,

I tried to use `kendzi3d` plugin in JOSM but the plugin fails to load.

I use [Java 10](http://www.oracle.com/technetwork/java/javase/downloads/index.html) (on Windows 10) :
```
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

Reading other issues, I tried both `josm.jnlp` and `josm-tested.jar` but both failed.

Thanks !
Looking forward to try that plugin :)

**Comment by kendzi** [comment]
what error you get?

**Comment by jbelien** [comment]
No error, just the standard without to "Disable" or "Keep" the plugin.

**Comment by kendzi** [comment]
Plugin is not fully compatible with modules in new java. Before application is upgraded please download josm jar to disk and run it with command:

```
java -jar --add-modules ALL-SYSTEM josm-tested.jar
```

**Comment by jbelien** [comment]
Awesome, it works 👍 

Thanks a lot !
