### ISSUE TITLE
Update to JOSM 15007

### ISSUE THREAD

**Issue by don-vip** [kendzi/kendzi3d#93]
I removed deprecated API Utils.setObjectsAccessible in JOSM [15007](https://josm.openstreetmap.de/changeset/15007/josm/#file10).

The plugin uses it and it must now call ReflectionUtils.setObjectsAccessible added in JOSM [14977](https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/tools/ReflectionUtils.java?rev=14977)

**Comment by don-vip** [comment]
Can you please update the plugin? It makes our integration test [fail](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.plugins/PluginHandlerTestIT/testValidityOfAvailablePlugins/).

**Comment by don-vip** [comment]
Hello,
as you know, we require that plugins listed on https://josm.openstreetmap.de/wiki/PluginsSource are reactive when dealing with updates.
Usually for low-quality plugins that are not being maintained we simply remove them when the author don't answer.
However this plugin is a great piece of software, we could directly deal with updates if it was transferred to the @JOSM organization. What do you think?

**Comment by don-vip** [comment]
Up? Without any answer that leaves us to two choices:
* remove plugin from https://josm.openstreetmap.de/wiki/PluginsSource
* fork the project

Ideally I would not want to go there, but we can't keep an incompatible plugin in the default list.

**Comment by kendzi** [comment]
Sorry, I was on holiday. I will manage it tomorrow

**Comment by kendzi** [comment]
Why everything happen to break when you are out ;)

**Comment by don-vip** [comment]
OK thanks a lot!

**Comment by kendzi** [comment]
fixed and released.

**Comment by don-vip** [comment]
Thanks! I don't know if it's related but now we have another error: https://github.com/kendzi/Simple3dBuildingsPreset/issues/3

**Comment by kendzi** [comment]
I saw it and fixed just now.
